apiVersion: v1
kind: Service
metadata:
  name: egress-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9444
      protocol: TCP
  selector:
    app.kubernetes.io/component: coil-egress-controller
