apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coil-ipam-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coil-ipam-controller
subjects:
- kind: ServiceAccount
  name: coil-ipam-controller
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coil-egress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coil-egress-controller
subjects:
- kind: ServiceAccount
  name: coil-egress-controller
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coild
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coild
subjects:
- kind: ServiceAccount
  name: coild
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coil-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coil-router
subjects:
- kind: ServiceAccount
  name: coil-router
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coil-egress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coil-egress
