apiVersion: v1
kind: ServiceAccount
metadata:
  name: coil-ipam-controller
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coil-egress-controller
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coild
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coil-router
  namespace: system
---
