
apiVersion: v1
kind: Service
metadata:
  name: ipam-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app.kubernetes.io/component: coil-ipam-controller
